package com.gym.management.domain.gym;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * null
 * @TableName gym_class
 */
@Data
public class GymClass implements Serializable {
    /**
     * self-increment id
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Long id;

    /**
     * class name
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String className;

    /**
     * class type
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Byte classType;

    /**
     * coach who own the class
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Long coachId;

    /**
     * 创建者
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String createBy;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Date createdTime;

    /**
     * 更新者
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String updateBy;

    /**
     * 更新时间
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Date modifiedTime;

    /**
     * 有效性
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Integer yn;

    /**
     * 备注信息
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gym_class
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private static final long serialVersionUID = 1L;
}