package com.gym.management.domain.gym;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * null
 * @TableName gym_card_info
 */
@Data
public class GymCardInfo implements Serializable {
    /**
     * self-increment id
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Long id;

    /**
     * foreign key
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Long customerId;

    /**
     * import card id
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String cardId;

    /**
     * membership start time
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Date membershipStart;

    /**
     * membership end time
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Date membershipEnd;

    /**
     * 卡类型
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Integer membership;

    /**
     * 创建者
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String createBy;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Date createdTime;

    /**
     * 更新者
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String updateBy;

    /**
     * 更新时间
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Date modifiedTime;

    /**
     * 有效性
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Integer yn;

    /**
     * 备注信息
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gym_card_info
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private static final long serialVersionUID = 1L;
}