package com.gym.management.domain.gym;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * null
 * @TableName gym_coach
 */
@Data
public class GymCoach implements Serializable {
    /**
     * self-increment id
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Long id;

    /**
     * coach name
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String coachName;

    /**
     * coach photo
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String coachPhoto;

    /**
     * coach age
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Integer coachAge;

    /**
     * describing the coach
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String coachDescription;

    /**
     * 创建者
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String createBy;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Date createdTime;

    /**
     * 更新者
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String updateBy;

    /**
     * 更新时间
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Date modifiedTime;

    /**
     * 有效性
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private Integer yn;

    /**
     * 备注信息
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gym_coach
     *
     * @mbg.generated 2021-03-21 23:38:04
     */
    private static final long serialVersionUID = 1L;
}