package com.gym.management.domain.entity.gym;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * null
 * @TableName gym_user
 */
@Data
public class GymUser implements Serializable {
    /**
     * self-increment id
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private Long id;

    /**
     * user name
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String name;

    /**
     * nick name
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String nickName;

    /**
     * phone number
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String phoneNum;

    /**
     * user birthday
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private Date birthday;

    /**
     * id card
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String nationalId;

    /**
     * invitor
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String invitor;

    /**
     * address
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String address;

    /**
     * mail address
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String mailAddress;

    /**
     * profession
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String profession;

    /**
     * annually income
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private Long annualIncome;

    /**
     * device information
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String deviceInfo;

    /**
     * fitting desire
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String fittingDesire;

    /**
     * 创建者
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String createBy;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private Date createdTime;

    /**
     * 更新者
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String updateBy;

    /**
     * 更新时间
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private Date modifiedTime;

    /**
     * 有效性
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private Integer yn;

    /**
     * 备注信息
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gym_user
     *
     * @mbg.generated 2021-03-14 00:26:58
     */
    private static final long serialVersionUID = 1L;
}