#tomcat config
spring:
  # 环境 dev|test|pro
  profiles:
    active: @spring.profiles.active@
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/templates/
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    encoding: utf-8
    # 禁用缓存
    cache: false
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  102400MB
      # 设置总上传的文件大小
      max-request-size:  102400MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
    aop:
      auto: true



mybatis:
  typeAliasesPackage: com.gym.management.domain
  mapperLocations: classpath*:dal/**/*Mapper.xml #实体扫描，多个package用逗号或者分号分隔
  executor-type: reuse #默认的执行器SIMPLE、执行器重用REUSE、执行器重用语句批量更新BATCH
  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login?lang=en_US
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
